import React, { createContext, useContext, useState, ReactNode } from 'react';
import { SupportedLanguage } from '../types/dr';

interface LanguageContextType {
  lang: SupportedLanguage;
  setLang: (l: SupportedLanguage) => void;
  t: (key: string) => string;
}

const translations: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    appTitle: 'NetraRakshak AI',
    appSubtitle: 'Explainable AI for Diabetic Retinopathy Screening in Rural India',
    sihBadge: 'Smart India Hackathon (SIH) Prototype',
    ruralPhcBadge: 'Rural PHC & ASHA Edition',
    offlineReady: 'Offline-Ready Edge AI',
    uploadTitle: 'Retinal Fundus Image Screening',
    uploadSubtitle: 'Upload a 45° macula-centered fundus photograph or select a clinical preset sample',
    dragDropText: 'Drag & drop retinal fundus photo here, or browse files',
    supportedFormats: 'Supports JPG, PNG, DICOM exports (Max 15MB)',
    patientDetails: 'Patient & PHC Information',
    patientName: 'Patient Name',
    patientAge: 'Age',
    gender: 'Gender',
    village: 'Village / PHC Center',
    eyeTested: 'Eye Examined',
    analyzeBtn: 'Run AI Screening & Explainability Analysis',
    analyzingText: 'Processing retinal fundus & computing Grad-CAM heatmaps...',
    orTryPresets: 'Or load a clinical benchmark preset for instant demo:',
    resultsTitle: 'Diagnostic Assessment & Explainable AI (XAI) Findings',
    gradCamTitle: 'Grad-CAM Explainability Heatmap Overlay',
    gradCamDesc: 'Visual proof of why the neural network made this diagnosis by highlighting key retinal lesions.',
    riskLow: 'Low Risk',
    riskMedium: 'Medium Risk',
    riskHigh: 'High Risk',
    riskCritical: 'Critical Risk',
    referralAction: 'Recommended Triage Action',
    timeframe: 'Recommended Window',
    qualityCheck: 'Image Quality & Gradability Verification',
    clarityScore: 'Sharpness Score',
    printReport: 'Print / Download Official Referral Slip',
    techStackBtn: 'Judge Demo / Python Backend Code',
    audioAdvice: 'Listen to Voice Guidance (ASHA Support)',
    resetBtn: 'Screen Another Patient',
  },
  hi: {
    appTitle: 'नेत्ररक्षक AI',
    appSubtitle: 'ग्रामीण भारत में डायबिटिक रेटिनोपैथी जांच हेतु व्याख्यात्मक AI प्रणाली',
    sihBadge: 'स्मार्ट इंडिया हैकथॉन (SIH) प्रोटोटाइप',
    ruralPhcBadge: 'ग्रामीण PHC एवं आशा कार्यकर्ता संस्करण',
    offlineReady: 'ऑफ़लाइन सक्षम AI',
    uploadTitle: 'आंख के पर्दे (रेटिना) की जांच',
    uploadSubtitle: 'रेटिना फंडस फोटो अपलोड करें या नीचे दिए गए क्लिनिकल सैंपल में से चुनें',
    dragDropText: 'यहां आंख के पर्दे की फोटो खींचकर छोड़ें या फाइल चुनें',
    supportedFormats: 'JPG, PNG, DICOM फाइलें समर्थित हैं',
    patientDetails: 'मरीज एवं स्वास्थ्य केंद्र का विवरण',
    patientName: 'मरीज का नाम',
    patientAge: 'उम्र',
    gender: 'लिंग',
    village: 'गांव / प्राथमिक स्वास्थ्य केंद्र (PHC)',
    eyeTested: 'जांची गई आंख',
    analyzeBtn: 'AI जांच और हीटमैप विश्लेषण शुरू करें',
    analyzingText: 'फोटो की जांच और Grad-CAM हीटमैप तैयार किया जा रहा है...',
    orTryPresets: 'या तुरंत डेमो देखने के लिए नीचे दिए गए सैंपल चुनें:',
    resultsTitle: 'जांच परिणाम और AI स्पष्टीकरण (Grad-CAM)',
    gradCamTitle: 'Grad-CAM हीटमैप (AI ने क्या देखकर फैसला लिया)',
    gradCamDesc: 'यह हीटमैप लाल रंग से दिखाता है कि AI ने आंख के किन हिस्सों में बीमारी के लक्षण देखे।',
    riskLow: 'कम जोखिम (स्वस्थ)',
    riskMedium: 'मध्यम जोखिम (जांच जरूरी)',
    riskHigh: 'अधिक जोखिम (गंभीर)',
    riskCritical: 'अत्यंत गंभीर (तुरंत अस्पताल)',
    referralAction: 'आशा कार्यकर्ता / डॉक्टर के लिए जरूरी निर्देश',
    timeframe: 'रेफरल समय सीमा',
    qualityCheck: 'फोटो की गुणवत्ता जांच',
    clarityScore: 'स्पष्टता स्कोर',
    printReport: 'अस्पताल रेफरल पर्ची प्रिंट / डाउनलोड करें',
    techStackBtn: 'जज डेमो / बैकएंड पायथन कोड',
    audioAdvice: 'आशा कार्यकर्ता के लिए वॉयस संदेश सुनें',
    resetBtn: 'नए मरीज की जांच करें',
  },
  ta: {
    appTitle: 'நேத்ரரக்ஷக் AI',
    appSubtitle: 'கிராமப்புற இந்தியாவில் நீரிழிவு விழித்திரை பரிசோதனைக்கான AI',
    sihBadge: 'SIH முன்மாதிரி',
    ruralPhcBadge: 'கிராமப்புற PHC பதிப்பு',
    offlineReady: 'ஆஃப்லைன் இயக்கம்',
    uploadTitle: 'விழித்திரை படம் பதிவேற்றம்',
    uploadSubtitle: 'விழித்திரை புகைப்படத்தைப் பதிவேற்றவும் அல்லது மாதிரியைத் தேர்ந்தெடுக்கவும்',
    dragDropText: 'புகைப்படத்தை இங்கே இழுத்து விடவும்',
    supportedFormats: 'JPG, PNG கோப்புகள்',
    patientDetails: 'நோயாளி விவரங்கள்',
    patientName: 'நோயாளி பெயர்',
    patientAge: 'வயது',
    gender: 'பாலினம்',
    village: 'கிராமம் / PHC',
    eyeTested: 'பரிசோதிக்கப்பட்ட கண்',
    analyzeBtn: 'AI பரிசோதனை தொடங்கு',
    analyzingText: 'படம் பகுப்பாய்வு செய்யப்படுகிறது...',
    orTryPresets: 'மாதிரி படத்தைத் தேர்வுசெய்யவும்:',
    resultsTitle: 'பரிசோதனை முடிவுகள் & Grad-CAM',
    gradCamTitle: 'Grad-CAM விளக்க வரைபடம்',
    gradCamDesc: 'AI எந்தப் பகுதியை அடிப்படையாகக் கொண்டு இந்த முடிவை எடுத்தது என்பதை வரைபடம் காட்டுகிறது.',
    riskLow: 'குறைந்த ஆபத்து',
    riskMedium: 'நடுத்தர ஆபத்து',
    riskHigh: 'அதிக ஆபத்து',
    riskCritical: 'அவசர சிகிச்சை தேவை',
    referralAction: 'பரிந்துரைக்கப்பட்ட நடவடிக்கை',
    timeframe: 'பரிந்துரை கால அளவு',
    qualityCheck: 'படத்தின் தரம்',
    clarityScore: 'தெளிவுத்திறன்',
    printReport: 'அறிக்கையை அச்சிடுக',
    techStackBtn: 'பைதான் குறியீடு & கட்டிடக்கலை',
    audioAdvice: 'ஆடியோ வழிகாட்டுதலைக் கேளுங்கள்',
    resetBtn: 'அடுத்த நோயாளி',
  },
  te: {
    appTitle: 'నేత్రరక్షక్ AI',
    appSubtitle: 'గ్రామీణ భారతదేశంలో డయాబెటిక్ రెటినోపతి స్క్రీనింగ్ కోసం AI',
    sihBadge: 'SIH ప్రాజెక్ట్',
    ruralPhcBadge: 'గ్రామీణ PHC ఎడిషన్',
    offlineReady: 'ఆఫ్‌లైన్ AI',
    uploadTitle: 'రెటినా ఇమేజ్ అప్‌లోడ్',
    uploadSubtitle: 'కంటి ఫోటోను అప్‌లోడ్ చేయండి లేదా నమూనాను ఎంచుకోండి',
    dragDropText: 'ఇక్కడ ఫోటోను డ్రాప్ చేయండి',
    supportedFormats: 'JPG, PNG ఫార్మాట్‌లు',
    patientDetails: 'రోగి వివరాలు',
    patientName: 'రోగి పేరు',
    patientAge: 'వయస్సు',
    gender: 'లింగం',
    village: 'గ్రామం / PHC',
    eyeTested: 'పరీక్షించిన కన్ను',
    analyzeBtn: 'AI స్క్రీనింగ్ ప్రారంభించండి',
    analyzingText: 'విశ్లేషణ జరుగుతోంది...',
    orTryPresets: 'నమూనాను ఎంచుకోండి:',
    resultsTitle: 'ఫలితాలు మరియు AI వివరణ',
    gradCamTitle: 'Grad-CAM హీట్‌మ్యాప్',
    gradCamDesc: 'AI నిర్ణయానికి గల కారణాన్ని హీట్‌మ్యాప్ చూపిస్తుంది.',
    riskLow: 'తక్కువ ప్రమాదం',
    riskMedium: 'మధ్యస్థ ప్రమాదం',
    riskHigh: 'ఎక్కువ ప్రమాదం',
    riskCritical: 'తీవ్రమైన ప్రమాదం',
    referralAction: 'సిఫార్సు చేయబడిన చర్య',
    timeframe: 'సమయ పరిమితి',
    qualityCheck: 'చిత్ర నాణ్యత',
    clarityScore: 'స్పష్టత స్కోరు',
    printReport: 'రిపోర్ట్ ప్రింట్ చేయండి',
    techStackBtn: 'పైథాన్ కోడ్ & ఆర్కిటెక్చర్',
    audioAdvice: 'వాయిస్ గైడెన్స్ వినండి',
    resetBtn: 'కొత్త రోగిని పరీక్షించండి',
  },
  bn: {
    appTitle: 'নেত্ররক্ষক AI',
    appSubtitle: 'গ্রামীণ ভারতে ডায়াবেটিক রেটিনোপ্যাথি স্ক্রিনিংয়ের জন্য AI',
    sihBadge: 'স্মার্ট ইন্ডিয়া হ্যাকাথন প্রোটোটাইপ',
    ruralPhcBadge: 'গ্রামীণ স্বাস্থ্যকেন্দ্র সংস্করণ',
    offlineReady: 'অফলাইন সক্ষম AI',
    uploadTitle: 'রেটিনা ছবি আপলোড',
    uploadSubtitle: 'চোখের রেটিনার ছবি আপলোড করুন অথবা নমুনা নির্বাচন করুন',
    dragDropText: 'এখানে ছবি আপলোড করুন',
    supportedFormats: 'JPG, PNG ফর্ম্যাট',
    patientDetails: 'রোগীর বিবরণ',
    patientName: 'রোগীর নাম',
    patientAge: 'বয়স',
    gender: 'লিঙ্গ',
    village: 'গ্রাম / স্বাস্থ্যকেন্দ্র',
    eyeTested: 'পরীক্ষিত চোখ',
    analyzeBtn: 'AI স্ক্রিনিং শুরু করুন',
    analyzingText: 'বিশ্লেষণ চলছে...',
    orTryPresets: 'নমুনা ছবি পরীক্ষা করুন:',
    resultsTitle: 'ফলাফল ও Grad-CAM ব্যাখ্যা',
    gradCamTitle: 'Grad-CAM হিটম্যাপ',
    gradCamDesc: 'AI কেন এই রোগ নির্ণয় করেছে তা হিটম্যাপের মাধ্যমে ব্যাখ্যা করা হয়েছে।',
    riskLow: 'কম ঝুঁকি',
    riskMedium: 'মাঝারি ঝুঁকি',
    riskHigh: 'উচ্চ ঝুঁকি',
    riskCritical: 'জরুরি অবস্থা',
    referralAction: 'প্রয়োজনীয় পদক্ষেপ',
    timeframe: 'সময়সীমা',
    qualityCheck: 'ছবির গুণমান যাচাই',
    clarityScore: 'স্পষ্টতা স্কোর',
    printReport: 'রেফারেল রিপোর্ট প্রিন্ট করুন',
    techStackBtn: 'পাইথন কোড ও আর্কিটেকচার',
    audioAdvice: 'ভয়েস নির্দেশিকা শুনুন',
    resetBtn: 'নতুন রোগী পরীক্ষা করুন',
  },
};

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLang: () => {},
  t: (key: string) => key,
});

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<SupportedLanguage>('en');

  const t = (key: string) => {
    return translations[lang]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
